typography_spectrum: 0.06291721621528268
color:
  brandStrength: 0.4321466132532805
  lightness: 0.5766102243214846
  saturation: 0.20104972715489566
  rhythmicContrast: 0.8115015325602144
  brandColors:
    - '#2C3E50'
    - '#E74C3C'
    - '#ECF0F1'
    - '#3498DB'
    - '#2980B9'
layout_spectrum: 0.4689480869565159
author:
  name: Antonio Jurado
  email: antonio.jurado@amistadcristianamexico.com
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/39902677-7705-46c0-a762-7811829e6c04.png
name: Amistad Cristiana A.C.
title: 'Juan 17:3'
description: >-
  Que te conozcan a ti el único Dios Verdadero y a Jesucristo a quien has
  envíado.
