layout_spectrum: 0.3552556501235813
typography_spectrum: 0.2930121554527432
color:
  brandStrength: 0.8745386796072125
  lightness: 0.8020057929679751
  saturation: 0.3358094124123454
  rhythmicContrast: 0.6977307952474803
  brandColors:
    - '#16193B'
    - '#35478C'
    - '#4E7AC7'
    - '#7FB2F0'
    - '#ADD5F7'
author:
  name: Antonio Jurado
  email: antonio.jurado@amistadcristianamexico.com
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/39902677-7705-46c0-a762-7811829e6c04.png
name: Amistad Cristiana A.C.
title: 'Juan 17:3'
description: >-
  Que te conozcan a ti el único Dios Verdadero y a Jesucristo a quien has
  envíado.
